extends Node

signal player_hit_by_rock
signal player_died
signal score_changed
signal mute_button_pressed
signal clicked_off_instructions
signal clicked_off_credits
signal instructions_clicked
signal credits_clicked
signal obstacle_spawned(obstacle: Node2D)
